before_script:
    - cd src/Cpp; sh ./mk_DataExample.sh; cd ../../

make:
    script:
        - cd src/Cpp/tests
        - g++ -g -o utData utData.cpp ../Data.cpp -I.. -std=c++11

test:
    script:
        - cd src/Cpp/tests
        - ./utData
